server:
 port: 8082
 servlet:
  context-path: /administrador
  
  spring:     
    datasource:
        platform: h2
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:test;
    h2:
      console:
        enabled: true
        path: /h2-console
    jpa:
      show-sql: true
  
  
  
